name: TestUI
version: 1.0.1
api: [4.0.0]
author: DaDevGuy
main: Rules\DaDevGuy\Rule

commands:
   test:
    description: "To Open Rules UI"
    usage: "/test"
    permission: testui.cmd

permissions:
  testui.cmd:
   default: true
